export const GET_REPO_REQUEST = "GET_REPO_REQUEST";
export const FETCH_REPO_DATA_SUCCESS = "FETCH_REPO_DATA_SUCCESS";
export const FETCH_REPO_DATA_FAILURE = "FETCH_REPO_DATA_FAILURE";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const GET_NEXT_PAGE = "GET_NEXT_PAGE";
